version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"  # Mudado para evitar conflitos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  webserver:
    image: apache/airflow:2.5.0
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    ports:
      - "8080:8080"
    volumes:
      - airflow_logs:/opt/airflow/logs
      - airflow_dags:/opt/airflow/dags
    networks:
      - airflow_network
    command: ["webserver"]

  scheduler:
    image: apache/airflow:2.5.0
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - webserver
    volumes:
      - airflow_logs:/opt/airflow/logs
      - airflow_dags:/opt/airflow/dags
    networks:
      - airflow_network
    command: ["scheduler"]

volumes:
  postgres_data:
  airflow_logs:
  airflow_dags:

networks:
  airflow_network:
